### ISSUE TITLE
Issues with mining in BTDEX client after plotting

### ISSUE THREAD

**Issue by dvvord** [btdex/btdex#162]
Using version 0.4.8 of BTDEX client (downloaded couple days ago). OS - Ubuntu 20.02
java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

After successful plot of 2 hard drives 0.8 TB each. And joining to pool with domain .de 
Mining button stays deactivated (this is first issue).

When checking Automatically start mining checkbox - mining starts if I restart client.
When mining is running after restart clicking a stop button causes an exception. (second issue)

java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:342)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at btdex.ui.MiningPanel$MineThread.run(MiningPanel.java:1287)

**Comment by jjos2372** [comment]
Hello, it takes 16 minutes after the join pool transaction confirms to be possible to mine. Please let us know if your issue continues after that.

Also thanks for reporting the second issue as well.

**Comment by dvvord** [comment]
I think I was waiting longer then 16 minutes and button was still inactive.

And for example next day - I see message "All set you can mine" when trying to join - and button is still in-active.

**Comment by jjos2372** [comment]
Ok, so looks like something else. If possible, join the BTDEX discord server or Burst telegram so we can debug this more easily.

**Comment by dvvord** [comment]
> Ok, so looks like something else. If possible, join the BTDEX discord server or Burst telegram so we can debug this more easily.

I'm under same nick in BTDEX discord

**Comment by dvvord** [comment]
Closing the issue - it seems resolved.
The issues was with my HDD dismounted. 
And while BTDEX kept the path it was not able to access them. (maybe a more explicit warning would be helpful)
